### ISSUE TITLE
Problem when run scrapy crawl

### ISSUE THREAD

**Issue by vokhuongcse0604** [scrapinghub/portia2code#2]
I have a project created by portia. I want to config database for this project because portia isn't support store data to database so I installed portia2code to convert portia project to scrapy. But when i crawl data by command : scrapy crawl <spider> -o data.csv in my project directory. It run OK, but it can't get any record into data.csv file as portiacrawl <project_path> <spider> -o data.csv of portia project. I don't understand. Please help me.

**Comment by ruairif** [comment]
Did you create the spider using the new version of Portia? Can you send the generated python file and the project json files so we can try to debug the problem?

If you want to export to a database using portia you can do so by writing an item writing middleware or pipeline. To enable the pipeline you need to add it to the `settings.py` file in your project you will also need to update the `scrapy.cfg` file so that it points to this settings file.
For more information about pipelines see [here](https://doc.scrapy.org/en/latest/topics/item-pipeline.html#activating-an-item-pipeline-component)

**Comment by vokhuongcse0604** [comment]
Thanks for reply me, 
I created portia project on localhost:6800 with spider on it, and i can crawl data to csv file following item specify by command: portiacrawl [project_path] [spider] -o data.csv. So I want to portia project can deploy by scrapyd-deploy as scrapy project but i failed. so i think i ll fail to setting pipeline. So that, i decided to convert portia project to scrapy project, it ok, but can't crawl any data.
this is my python file generate: 
class Allrecipes(BasePortiaSpider):
    name = "allrecipes.com"
    allowed_domains = [u'allrecipes.com']
    start_urls = [u'http://allrecipes.com/recipe/137411/barb-a-fu/?internalSource=rotd&referringId=84&referringContentType=recipe%20hub&clickId=cardslot%201',
                  u'http://allrecipes.com/recipe/62423/beer-lime-grilled-chicken/?internalSource=staff%20pick&referringId=1232&referringContentType=recipe%20hub&clickId=cardslot%202']

   rules = [
        Rule(
            LinkExtractor(
                allow=(),
                deny=()
            ),
            callback='parse_item',
            follow=False
        )
    ]
item = [ [] ]

**Comment by ruairif** [comment]
There are no annotations there so it is quite possible that you created your spider using the current master version of Portia.
Portia2Code only work with spiders created with a newer version of Portia (available in the `portia-orm-on-django` branch)

**Comment by vokhuongcse0604** [comment]
Yes, i just clone it. I' ll clone again. thank you very much.
